// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJUL2xpdymnfg1Ql5jl_augh9HJyltqI4',
    appId: '1:641676525528:web:2fc7d25799e46a243f7cad',
    messagingSenderId: '641676525528',
    projectId: 'past-calculator',
    authDomain: 'past-calculator.firebaseapp.com',
    storageBucket: 'past-calculator.appspot.com',
    measurementId: 'G-CH3S9HT624',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5tTkSQq_PX_6o_0Jl99wNQRJp7plESzE',
    appId: '1:641676525528:android:15fd1038e1122c533f7cad',
    messagingSenderId: '641676525528',
    projectId: 'past-calculator',
    storageBucket: 'past-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKnFIZlqiXJh0eRi--TZ4Hw_RJDg_9zwQ',
    appId: '1:641676525528:ios:da45d6c8a3539cf73f7cad',
    messagingSenderId: '641676525528',
    projectId: 'past-calculator',
    storageBucket: 'past-calculator.appspot.com',
    iosBundleId: 'com.calculator.pastCalculator',
  );
}
